version: '3.8'

services:
  fukuro:
    build: .
    container_name: fukuro
    volumes:
      - ./:/app
    user: "${UID}:${GID}"
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia